package com.erp.china.demo.util;

import java.util.Random;

/**
 * @author Robby B. Setyo
 * 
 * Description: generate a primary key for a new row of a table
 */
public class KeyGenerator {
	private int requestRandomAppend = 10;
	Random rand = null; 

	public KeyGenerator() {
		rand = new Random();
	}

	//the id can be generated by System.currentTimeMillis() + some random generated number
	public String generateId() {
		String timeNum = (new Long(System.currentTimeMillis())).toString();
		return (timeNum.substring(8) + getRandomNumber());
	}

	private String getRandomNumber() {
		String appendNum = Integer.toString(rand.nextInt(10));
		for(int i = 1; i < requestRandomAppend; i++) {
			//generate a number that from 0 to 9(inclusive)
			appendNum += rand.nextInt(10);
		}
		return appendNum;
	}
}